### ISSUE TITLE
Keep骑行数据同步有计划要做吗？

### ISSUE THREAD

**Issue by wancheng** [geekplux/activities#3]

**Comment by geekplux** [comment]
直接用 https://github.com/yihong0618/running_page

**Comment by wancheng** [comment]
running_page脚本只能同步跑步数据

**Comment by geekplux** [comment]
😂竟然只能同步跑步数据？让 @yihong0618 搞个所有类型数据都能同步的项目

**Comment by yihong0618** [comment]
骑行的目前路径需要解密，我抽个时间试试吧。
https://github.com/yihong0618/running_page/issues/254
